package org.pachinko.dao;

import java.util.List;

import org.pachinko.entity.ChongZhi;

public interface IChongzhiDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(ChongZhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChongZhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    ChongZhi selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    ChongZhi selectBySellerId(Integer sellerId);


    List<ChongZhi> queryChongZhiList();

}