package org.pachinko.dao;

import java.util.List;

import org.pachinko.dto.FeeParam;
import org.pachinko.entity.FeeDetail;

public interface IFeeDetailDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(FeeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    //int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FeeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    FeeDetail selectByPrimaryKey(Integer orderId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<FeeDetail> selectListByInvitationUserId(FeeParam feeParam);

}