package org.pachinko.dao;

import java.util.List;

import org.pachinko.dto.OrderPageQuery;
import org.pachinko.entity.Order;

public interface IOrderDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Long id);


    List<Order> queryOrderListByUserId(OrderPageQuery pageQuery);

    List<Order> queryOrderList(OrderPageQuery pageQuery);

}